import jsPDF from 'jspdf';

// ─── Color Palette ────────────────────────────────────────────────────────────
const C = {
    headerBg: [15, 23, 42],       // Deep navy
    primary: [255, 140, 0],      // Orange / gold accent
    darkHeader: [30, 41, 59],       // Dark table header
    white: [255, 255, 255],
    bodyText: [30, 41, 59],
    mutedText: [100, 116, 139],
    rowAlt: [248, 250, 252],
    border: [226, 232, 240],
    successGreen: [16, 185, 129],
    warningAmber: [245, 158, 11],
    dangerRed: [239, 68, 68],
};

const setFill = (doc, c) => doc.setFillColor(...c);
const setText = (doc, c) => doc.setTextColor(...c);
const setDraw = (doc, c) => doc.setDrawColor(...c);

const truncate = (str, max = 35) => {
    const s = str != null ? String(str) : '-';
    return s.length > max ? s.slice(0, max - 1) + '…' : s;
};

// ─── Load logo as base64 ──────────────────────────────────────────────────────
const loadLogoBase64 = () => {
    return new Promise((resolve) => {
        const img = new Image();
        img.crossOrigin = 'anonymous';
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.naturalWidth;
            canvas.height = img.naturalHeight;
            const ctx = canvas.getContext('2d');
            ctx.drawImage(img, 0, 0);
            resolve(canvas.toDataURL('image/png'));
        };
        img.onerror = () => resolve(null); // gracefully skip if logo missing
        img.src = '/logo.png';
    });
};

// ─── Header ───────────────────────────────────────────────────────────────────
const drawHeader = (doc, title, pageWidth, logoBase64) => {
    const H = 52;

    // Navy background
    setFill(doc, C.headerBg);
    doc.rect(0, 0, pageWidth, H, 'F');

    // Orange left accent bar
    setFill(doc, C.primary);
    doc.rect(0, 0, 4, H, 'F');

    // Logo (if loaded)
    const logoSize = 20;
    const logoX = 10;
    const logoY = (H - logoSize) / 2;
    if (logoBase64) {
        doc.addImage(logoBase64, 'PNG', logoX, logoY, logoSize, logoSize);
    }

    // Company name & report title (to the right of the logo)
    const textX = logoBase64 ? logoX + logoSize + 5 : 12;

    // Company name: "Nextgen Shield (Private) Limited"
    setText(doc, C.primary);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Nextgen Shield (Private) Limited', textX, 20);

    // Report title (white, slightly smaller)
    setText(doc, C.white);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(title, textX, 32);

    // Thin orange separator line at bottom of header
    setDraw(doc, C.primary);
    doc.setLineWidth(0.8);
    doc.line(0, H, pageWidth, H);

    return H;
};

// ─── Info Table ───────────────────────────────────────────────────────────────
const drawInfoTable = (doc, metadata, startY, pageWidth) => {
    const margin = 14;
    const tableW = pageWidth - margin * 2;
    const colW = tableW / 4;
    const hH = 8, vH = 9;

    setText(doc, C.bodyText);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Report Information', margin, startY + 5);

    const tY = startY + 8;

    // Header row (orange)
    setFill(doc, C.primary);
    doc.rect(margin, tY, tableW, hH, 'F');
    setText(doc, C.headerBg);
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    ['Generated By', 'Report Status', 'Summary Date', 'Scope'].forEach((h, i) => {
        doc.text(h, margin + i * colW + 3, tY + 5.5);
    });

    // Value row (white)
    setFill(doc, C.white);
    setDraw(doc, C.border);
    doc.setLineWidth(0.3);
    doc.rect(margin, tY + hH, tableW, vH, 'FD');
    setText(doc, C.bodyText);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    [
        metadata.generatedBy || 'System Admin',
        'Complete',
        new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }),
        metadata.range || 'Live Feed',
    ].forEach((v, i) => {
        doc.text(String(v), margin + i * colW + 3, tY + hH + 6);
    });

    return tY + hH + vH + 8;
};

// ─── Manual Table Drawing ─────────────────────────────────────────────────────
const drawTable = (doc, columns, rows, startY, pageWidth) => {
    const margin = 14;
    const tableW = pageWidth - margin * 2;
    const colW = tableW / columns.length;
    const rowH = 8;
    const headerH = 9;

    let y = startY;

    const drawRowHeader = () => {
        setFill(doc, C.darkHeader);
        doc.rect(margin, y, tableW, headerH, 'F');
        setText(doc, C.white);
        doc.setFontSize(7.5);
        doc.setFont('helvetica', 'bold');
        columns.forEach((col, i) => {
            doc.text(col.header.toUpperCase(), margin + i * colW + colW / 2, y + 6, { align: 'center' });
        });
        y += headerH;
    };

    const checkPageBreak = () => {
        const pageH = doc.internal.pageSize.getHeight();
        if (y + rowH > pageH - 20) {
            doc.addPage();
            y = 20;
            drawRowHeader();
        }
    };

    drawRowHeader();

    rows.forEach((row, rowIdx) => {
        checkPageBreak();

        if (rowIdx % 2 === 1) {
            setFill(doc, C.rowAlt);
            doc.rect(margin, y, tableW, rowH, 'F');
        }

        setDraw(doc, C.border);
        doc.setLineWidth(0.2);
        doc.rect(margin, y, tableW, rowH, 'D');

        row.forEach((cell, i) => {
            const cellText = String(cell ?? '-');
            const lower = cellText.toLowerCase();

            if (['checked-in', 'approved', 'confirmed', 'complete', 'scheduled'].some(s => lower.includes(s))) {
                setText(doc, C.successGreen);
                doc.setFont('helvetica', 'bold');
            } else if (['pending', 'in progress', 'meeting requested'].some(s => lower.includes(s))) {
                setText(doc, C.warningAmber);
                doc.setFont('helvetica', 'bold');
            } else if (['denied', 'rejected', 'cancelled'].some(s => lower.includes(s))) {
                setText(doc, C.dangerRed);
                doc.setFont('helvetica', 'bold');
            } else if (i === 0) {
                setText(doc, C.bodyText);
                doc.setFont('helvetica', 'bold');
            } else {
                setText(doc, C.bodyText);
                doc.setFont('helvetica', 'normal');
            }

            doc.setFontSize(7);
            const clipped = doc.splitTextToSize(cellText, colW - 4)[0] || cellText;
            doc.text(clipped, margin + i * colW + 3, y + 5.5);
        });

        y += rowH;
    });

    return y;
};

// ─── Footer ───────────────────────────────────────────────────────────────────
const drawFooter = (doc, pageWidth, pageHeight, pageNum, pageCount) => {
    const y = pageHeight - 12;
    setDraw(doc, C.border);
    doc.setLineWidth(0.3);
    doc.line(14, y - 3, pageWidth - 14, y - 3);

    setText(doc, C.mutedText);
    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'normal');
    doc.text('Nextgen Shield (Private) Limited  •  Confidential', 14, y + 1);
    doc.text(`Page ${pageNum} of ${pageCount}`, pageWidth - 14, y + 1, { align: 'right' });
};

// ─── Main Export ──────────────────────────────────────────────────────────────
export const exportToPDF = async (options) => {
    const { title, data, columns, filename, metadata = {} } = options;

    // Load logo before building PDF
    const logoBase64 = await loadLogoBase64();

    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // 1. Header (logo + company name + report title)
    let y = drawHeader(doc, title, pageWidth, logoBase64) + 8;

    // 2. Info table
    y = drawInfoTable(doc, metadata, y, pageWidth);

    // 3. Section label
    setText(doc, C.bodyText);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Detailed Records', 14, y + 4);
    y += 8;

    // 4. Build table rows (flatten React elements to plain strings)
    const tableRows = data.map(row =>
        columns.map(col => {
            let val = row[col.key];
            if (col.render) {
                try {
                    const rendered = col.render(val, row);
                    if (rendered !== null && typeof rendered === 'object' && rendered.$$typeof) {
                        val = val != null ? String(val) : '-';
                    } else {
                        val = rendered;
                    }
                } catch (_) { /* keep raw val */ }
            }
            return truncate(val);
        })
    );

    // 5. Draw table
    drawTable(doc, columns, tableRows, y, pageWidth);

    // 6. Footer on every page
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        drawFooter(doc, pageWidth, pageHeight, i, pageCount);
    }

    doc.save(filename.endsWith('.pdf') ? filename : `${filename}.pdf`);
};
